// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: objects_3D.proto

#ifndef GOOGLE_PROTOBUF_INCLUDED_objects_5f3D_2eproto
#define GOOGLE_PROTOBUF_INCLUDED_objects_5f3D_2eproto

#include <limits>
#include <string>

#include <google/protobuf/port_def.inc>
#if PROTOBUF_VERSION < 3021000
#error This file was generated by a newer version of protoc which is
#error incompatible with your Protocol Buffer headers. Please update
#error your headers.
#endif
#if 3021012 < PROTOBUF_MIN_PROTOC_VERSION
#error This file was generated by an older version of protoc which is
#error incompatible with your Protocol Buffer headers. Please
#error regenerate this file with a newer version of protoc.
#endif

#include <google/protobuf/port_undef.inc>
#include <google/protobuf/io/coded_stream.h>
#include <google/protobuf/arena.h>
#include <google/protobuf/arenastring.h>
#include <google/protobuf/generated_message_util.h>
#include <google/protobuf/metadata_lite.h>
#include <google/protobuf/generated_message_reflection.h>
#include <google/protobuf/message.h>
#include <google/protobuf/repeated_field.h>  // IWYU pragma: export
#include <google/protobuf/extension_set.h>  // IWYU pragma: export
#include <google/protobuf/unknown_field_set.h>
// @@protoc_insertion_point(includes)
#include <google/protobuf/port_def.inc>
#define PROTOBUF_INTERNAL_EXPORT_objects_5f3D_2eproto
PROTOBUF_NAMESPACE_OPEN
namespace internal {
class AnyMetadata;
}  // namespace internal
PROTOBUF_NAMESPACE_CLOSE

// Internal implementation detail -- do not use these members.
struct TableStruct_objects_5f3D_2eproto {
  static const uint32_t offsets[];
};
extern const ::PROTOBUF_NAMESPACE_ID::internal::DescriptorTable descriptor_table_objects_5f3D_2eproto;
class Object3D_msg;
struct Object3D_msgDefaultTypeInternal;
extern Object3D_msgDefaultTypeInternal _Object3D_msg_default_instance_;
class Objects3D_msg;
struct Objects3D_msgDefaultTypeInternal;
extern Objects3D_msgDefaultTypeInternal _Objects3D_msg_default_instance_;
PROTOBUF_NAMESPACE_OPEN
template<> ::Object3D_msg* Arena::CreateMaybeMessage<::Object3D_msg>(Arena*);
template<> ::Objects3D_msg* Arena::CreateMaybeMessage<::Objects3D_msg>(Arena*);
PROTOBUF_NAMESPACE_CLOSE

// ===================================================================

class Object3D_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Object3D_msg) */ {
 public:
  inline Object3D_msg() : Object3D_msg(nullptr) {}
  ~Object3D_msg() override;
  explicit PROTOBUF_CONSTEXPR Object3D_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Object3D_msg(const Object3D_msg& from);
  Object3D_msg(Object3D_msg&& from) noexcept
    : Object3D_msg() {
    *this = ::std::move(from);
  }

  inline Object3D_msg& operator=(const Object3D_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Object3D_msg& operator=(Object3D_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Object3D_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Object3D_msg* internal_default_instance() {
    return reinterpret_cast<const Object3D_msg*>(
               &_Object3D_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    0;

  friend void swap(Object3D_msg& a, Object3D_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Object3D_msg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Object3D_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Object3D_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Object3D_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Object3D_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Object3D_msg& from) {
    Object3D_msg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Object3D_msg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Object3D_msg";
  }
  protected:
  explicit Object3D_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kLabelFieldNumber = 2,
    kIdFieldNumber = 1,
    kXFieldNumber = 3,
    kYFieldNumber = 4,
    kZFieldNumber = 5,
    kOrientationFieldNumber = 6,
    kVyFieldNumber = 7,
    kWidthFieldNumber = 8,
    kLengthFieldNumber = 9,
    kHeightFieldNumber = 10,
  };
  // string label = 2;
  void clear_label();
  const std::string& label() const;
  template <typename ArgT0 = const std::string&, typename... ArgT>
  void set_label(ArgT0&& arg0, ArgT... args);
  std::string* mutable_label();
  PROTOBUF_NODISCARD std::string* release_label();
  void set_allocated_label(std::string* label);
  private:
  const std::string& _internal_label() const;
  inline PROTOBUF_ALWAYS_INLINE void _internal_set_label(const std::string& value);
  std::string* _internal_mutable_label();
  public:

  // int32 id = 1;
  void clear_id();
  int32_t id() const;
  void set_id(int32_t value);
  private:
  int32_t _internal_id() const;
  void _internal_set_id(int32_t value);
  public:

  // float x = 3;
  void clear_x();
  float x() const;
  void set_x(float value);
  private:
  float _internal_x() const;
  void _internal_set_x(float value);
  public:

  // float y = 4;
  void clear_y();
  float y() const;
  void set_y(float value);
  private:
  float _internal_y() const;
  void _internal_set_y(float value);
  public:

  // float z = 5;
  void clear_z();
  float z() const;
  void set_z(float value);
  private:
  float _internal_z() const;
  void _internal_set_z(float value);
  public:

  // float orientation = 6;
  void clear_orientation();
  float orientation() const;
  void set_orientation(float value);
  private:
  float _internal_orientation() const;
  void _internal_set_orientation(float value);
  public:

  // float vy = 7;
  void clear_vy();
  float vy() const;
  void set_vy(float value);
  private:
  float _internal_vy() const;
  void _internal_set_vy(float value);
  public:

  // float width = 8;
  void clear_width();
  float width() const;
  void set_width(float value);
  private:
  float _internal_width() const;
  void _internal_set_width(float value);
  public:

  // float length = 9;
  void clear_length();
  float length() const;
  void set_length(float value);
  private:
  float _internal_length() const;
  void _internal_set_length(float value);
  public:

  // float height = 10;
  void clear_height();
  float height() const;
  void set_height(float value);
  private:
  float _internal_height() const;
  void _internal_set_height(float value);
  public:

  // @@protoc_insertion_point(class_scope:Object3D_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::internal::ArenaStringPtr label_;
    int32_t id_;
    float x_;
    float y_;
    float z_;
    float orientation_;
    float vy_;
    float width_;
    float length_;
    float height_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_objects_5f3D_2eproto;
};
// -------------------------------------------------------------------

class Objects3D_msg final :
    public ::PROTOBUF_NAMESPACE_ID::Message /* @@protoc_insertion_point(class_definition:Objects3D_msg) */ {
 public:
  inline Objects3D_msg() : Objects3D_msg(nullptr) {}
  ~Objects3D_msg() override;
  explicit PROTOBUF_CONSTEXPR Objects3D_msg(::PROTOBUF_NAMESPACE_ID::internal::ConstantInitialized);

  Objects3D_msg(const Objects3D_msg& from);
  Objects3D_msg(Objects3D_msg&& from) noexcept
    : Objects3D_msg() {
    *this = ::std::move(from);
  }

  inline Objects3D_msg& operator=(const Objects3D_msg& from) {
    CopyFrom(from);
    return *this;
  }
  inline Objects3D_msg& operator=(Objects3D_msg&& from) noexcept {
    if (this == &from) return *this;
    if (GetOwningArena() == from.GetOwningArena()
  #ifdef PROTOBUF_FORCE_COPY_IN_MOVE
        && GetOwningArena() != nullptr
  #endif  // !PROTOBUF_FORCE_COPY_IN_MOVE
    ) {
      InternalSwap(&from);
    } else {
      CopyFrom(from);
    }
    return *this;
  }

  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* descriptor() {
    return GetDescriptor();
  }
  static const ::PROTOBUF_NAMESPACE_ID::Descriptor* GetDescriptor() {
    return default_instance().GetMetadata().descriptor;
  }
  static const ::PROTOBUF_NAMESPACE_ID::Reflection* GetReflection() {
    return default_instance().GetMetadata().reflection;
  }
  static const Objects3D_msg& default_instance() {
    return *internal_default_instance();
  }
  static inline const Objects3D_msg* internal_default_instance() {
    return reinterpret_cast<const Objects3D_msg*>(
               &_Objects3D_msg_default_instance_);
  }
  static constexpr int kIndexInFileMessages =
    1;

  friend void swap(Objects3D_msg& a, Objects3D_msg& b) {
    a.Swap(&b);
  }
  inline void Swap(Objects3D_msg* other) {
    if (other == this) return;
  #ifdef PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() != nullptr &&
        GetOwningArena() == other->GetOwningArena()) {
   #else  // PROTOBUF_FORCE_COPY_IN_SWAP
    if (GetOwningArena() == other->GetOwningArena()) {
  #endif  // !PROTOBUF_FORCE_COPY_IN_SWAP
      InternalSwap(other);
    } else {
      ::PROTOBUF_NAMESPACE_ID::internal::GenericSwap(this, other);
    }
  }
  void UnsafeArenaSwap(Objects3D_msg* other) {
    if (other == this) return;
    GOOGLE_DCHECK(GetOwningArena() == other->GetOwningArena());
    InternalSwap(other);
  }

  // implements Message ----------------------------------------------

  Objects3D_msg* New(::PROTOBUF_NAMESPACE_ID::Arena* arena = nullptr) const final {
    return CreateMaybeMessage<Objects3D_msg>(arena);
  }
  using ::PROTOBUF_NAMESPACE_ID::Message::CopyFrom;
  void CopyFrom(const Objects3D_msg& from);
  using ::PROTOBUF_NAMESPACE_ID::Message::MergeFrom;
  void MergeFrom( const Objects3D_msg& from) {
    Objects3D_msg::MergeImpl(*this, from);
  }
  private:
  static void MergeImpl(::PROTOBUF_NAMESPACE_ID::Message& to_msg, const ::PROTOBUF_NAMESPACE_ID::Message& from_msg);
  public:
  PROTOBUF_ATTRIBUTE_REINITIALIZES void Clear() final;
  bool IsInitialized() const final;

  size_t ByteSizeLong() const final;
  const char* _InternalParse(const char* ptr, ::PROTOBUF_NAMESPACE_ID::internal::ParseContext* ctx) final;
  uint8_t* _InternalSerialize(
      uint8_t* target, ::PROTOBUF_NAMESPACE_ID::io::EpsCopyOutputStream* stream) const final;
  int GetCachedSize() const final { return _impl_._cached_size_.Get(); }

  private:
  void SharedCtor(::PROTOBUF_NAMESPACE_ID::Arena* arena, bool is_message_owned);
  void SharedDtor();
  void SetCachedSize(int size) const final;
  void InternalSwap(Objects3D_msg* other);

  private:
  friend class ::PROTOBUF_NAMESPACE_ID::internal::AnyMetadata;
  static ::PROTOBUF_NAMESPACE_ID::StringPiece FullMessageName() {
    return "Objects3D_msg";
  }
  protected:
  explicit Objects3D_msg(::PROTOBUF_NAMESPACE_ID::Arena* arena,
                       bool is_message_owned = false);
  public:

  static const ClassData _class_data_;
  const ::PROTOBUF_NAMESPACE_ID::Message::ClassData*GetClassData() const final;

  ::PROTOBUF_NAMESPACE_ID::Metadata GetMetadata() const final;

  // nested types ----------------------------------------------------

  // accessors -------------------------------------------------------

  enum : int {
    kObjectsFieldNumber = 1,
  };
  // repeated .Object3D_msg objects = 1;
  int objects_size() const;
  private:
  int _internal_objects_size() const;
  public:
  void clear_objects();
  ::Object3D_msg* mutable_objects(int index);
  ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Object3D_msg >*
      mutable_objects();
  private:
  const ::Object3D_msg& _internal_objects(int index) const;
  ::Object3D_msg* _internal_add_objects();
  public:
  const ::Object3D_msg& objects(int index) const;
  ::Object3D_msg* add_objects();
  const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Object3D_msg >&
      objects() const;

  // @@protoc_insertion_point(class_scope:Objects3D_msg)
 private:
  class _Internal;

  template <typename T> friend class ::PROTOBUF_NAMESPACE_ID::Arena::InternalHelper;
  typedef void InternalArenaConstructable_;
  typedef void DestructorSkippable_;
  struct Impl_ {
    ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Object3D_msg > objects_;
    mutable ::PROTOBUF_NAMESPACE_ID::internal::CachedSize _cached_size_;
  };
  union { Impl_ _impl_; };
  friend struct ::TableStruct_objects_5f3D_2eproto;
};
// ===================================================================


// ===================================================================

#ifdef __GNUC__
  #pragma GCC diagnostic push
  #pragma GCC diagnostic ignored "-Wstrict-aliasing"
#endif  // __GNUC__
// Object3D_msg

// int32 id = 1;
inline void Object3D_msg::clear_id() {
  _impl_.id_ = 0;
}
inline int32_t Object3D_msg::_internal_id() const {
  return _impl_.id_;
}
inline int32_t Object3D_msg::id() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.id)
  return _internal_id();
}
inline void Object3D_msg::_internal_set_id(int32_t value) {
  
  _impl_.id_ = value;
}
inline void Object3D_msg::set_id(int32_t value) {
  _internal_set_id(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.id)
}

// string label = 2;
inline void Object3D_msg::clear_label() {
  _impl_.label_.ClearToEmpty();
}
inline const std::string& Object3D_msg::label() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.label)
  return _internal_label();
}
template <typename ArgT0, typename... ArgT>
inline PROTOBUF_ALWAYS_INLINE
void Object3D_msg::set_label(ArgT0&& arg0, ArgT... args) {
 
 _impl_.label_.Set(static_cast<ArgT0 &&>(arg0), args..., GetArenaForAllocation());
  // @@protoc_insertion_point(field_set:Object3D_msg.label)
}
inline std::string* Object3D_msg::mutable_label() {
  std::string* _s = _internal_mutable_label();
  // @@protoc_insertion_point(field_mutable:Object3D_msg.label)
  return _s;
}
inline const std::string& Object3D_msg::_internal_label() const {
  return _impl_.label_.Get();
}
inline void Object3D_msg::_internal_set_label(const std::string& value) {
  
  _impl_.label_.Set(value, GetArenaForAllocation());
}
inline std::string* Object3D_msg::_internal_mutable_label() {
  
  return _impl_.label_.Mutable(GetArenaForAllocation());
}
inline std::string* Object3D_msg::release_label() {
  // @@protoc_insertion_point(field_release:Object3D_msg.label)
  return _impl_.label_.Release();
}
inline void Object3D_msg::set_allocated_label(std::string* label) {
  if (label != nullptr) {
    
  } else {
    
  }
  _impl_.label_.SetAllocated(label, GetArenaForAllocation());
#ifdef PROTOBUF_FORCE_COPY_DEFAULT_STRING
  if (_impl_.label_.IsDefault()) {
    _impl_.label_.Set("", GetArenaForAllocation());
  }
#endif // PROTOBUF_FORCE_COPY_DEFAULT_STRING
  // @@protoc_insertion_point(field_set_allocated:Object3D_msg.label)
}

// float x = 3;
inline void Object3D_msg::clear_x() {
  _impl_.x_ = 0;
}
inline float Object3D_msg::_internal_x() const {
  return _impl_.x_;
}
inline float Object3D_msg::x() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.x)
  return _internal_x();
}
inline void Object3D_msg::_internal_set_x(float value) {
  
  _impl_.x_ = value;
}
inline void Object3D_msg::set_x(float value) {
  _internal_set_x(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.x)
}

// float y = 4;
inline void Object3D_msg::clear_y() {
  _impl_.y_ = 0;
}
inline float Object3D_msg::_internal_y() const {
  return _impl_.y_;
}
inline float Object3D_msg::y() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.y)
  return _internal_y();
}
inline void Object3D_msg::_internal_set_y(float value) {
  
  _impl_.y_ = value;
}
inline void Object3D_msg::set_y(float value) {
  _internal_set_y(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.y)
}

// float z = 5;
inline void Object3D_msg::clear_z() {
  _impl_.z_ = 0;
}
inline float Object3D_msg::_internal_z() const {
  return _impl_.z_;
}
inline float Object3D_msg::z() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.z)
  return _internal_z();
}
inline void Object3D_msg::_internal_set_z(float value) {
  
  _impl_.z_ = value;
}
inline void Object3D_msg::set_z(float value) {
  _internal_set_z(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.z)
}

// float orientation = 6;
inline void Object3D_msg::clear_orientation() {
  _impl_.orientation_ = 0;
}
inline float Object3D_msg::_internal_orientation() const {
  return _impl_.orientation_;
}
inline float Object3D_msg::orientation() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.orientation)
  return _internal_orientation();
}
inline void Object3D_msg::_internal_set_orientation(float value) {
  
  _impl_.orientation_ = value;
}
inline void Object3D_msg::set_orientation(float value) {
  _internal_set_orientation(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.orientation)
}

// float vy = 7;
inline void Object3D_msg::clear_vy() {
  _impl_.vy_ = 0;
}
inline float Object3D_msg::_internal_vy() const {
  return _impl_.vy_;
}
inline float Object3D_msg::vy() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.vy)
  return _internal_vy();
}
inline void Object3D_msg::_internal_set_vy(float value) {
  
  _impl_.vy_ = value;
}
inline void Object3D_msg::set_vy(float value) {
  _internal_set_vy(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.vy)
}

// float width = 8;
inline void Object3D_msg::clear_width() {
  _impl_.width_ = 0;
}
inline float Object3D_msg::_internal_width() const {
  return _impl_.width_;
}
inline float Object3D_msg::width() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.width)
  return _internal_width();
}
inline void Object3D_msg::_internal_set_width(float value) {
  
  _impl_.width_ = value;
}
inline void Object3D_msg::set_width(float value) {
  _internal_set_width(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.width)
}

// float length = 9;
inline void Object3D_msg::clear_length() {
  _impl_.length_ = 0;
}
inline float Object3D_msg::_internal_length() const {
  return _impl_.length_;
}
inline float Object3D_msg::length() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.length)
  return _internal_length();
}
inline void Object3D_msg::_internal_set_length(float value) {
  
  _impl_.length_ = value;
}
inline void Object3D_msg::set_length(float value) {
  _internal_set_length(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.length)
}

// float height = 10;
inline void Object3D_msg::clear_height() {
  _impl_.height_ = 0;
}
inline float Object3D_msg::_internal_height() const {
  return _impl_.height_;
}
inline float Object3D_msg::height() const {
  // @@protoc_insertion_point(field_get:Object3D_msg.height)
  return _internal_height();
}
inline void Object3D_msg::_internal_set_height(float value) {
  
  _impl_.height_ = value;
}
inline void Object3D_msg::set_height(float value) {
  _internal_set_height(value);
  // @@protoc_insertion_point(field_set:Object3D_msg.height)
}

// -------------------------------------------------------------------

// Objects3D_msg

// repeated .Object3D_msg objects = 1;
inline int Objects3D_msg::_internal_objects_size() const {
  return _impl_.objects_.size();
}
inline int Objects3D_msg::objects_size() const {
  return _internal_objects_size();
}
inline void Objects3D_msg::clear_objects() {
  _impl_.objects_.Clear();
}
inline ::Object3D_msg* Objects3D_msg::mutable_objects(int index) {
  // @@protoc_insertion_point(field_mutable:Objects3D_msg.objects)
  return _impl_.objects_.Mutable(index);
}
inline ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Object3D_msg >*
Objects3D_msg::mutable_objects() {
  // @@protoc_insertion_point(field_mutable_list:Objects3D_msg.objects)
  return &_impl_.objects_;
}
inline const ::Object3D_msg& Objects3D_msg::_internal_objects(int index) const {
  return _impl_.objects_.Get(index);
}
inline const ::Object3D_msg& Objects3D_msg::objects(int index) const {
  // @@protoc_insertion_point(field_get:Objects3D_msg.objects)
  return _internal_objects(index);
}
inline ::Object3D_msg* Objects3D_msg::_internal_add_objects() {
  return _impl_.objects_.Add();
}
inline ::Object3D_msg* Objects3D_msg::add_objects() {
  ::Object3D_msg* _add = _internal_add_objects();
  // @@protoc_insertion_point(field_add:Objects3D_msg.objects)
  return _add;
}
inline const ::PROTOBUF_NAMESPACE_ID::RepeatedPtrField< ::Object3D_msg >&
Objects3D_msg::objects() const {
  // @@protoc_insertion_point(field_list:Objects3D_msg.objects)
  return _impl_.objects_;
}

#ifdef __GNUC__
  #pragma GCC diagnostic pop
#endif  // __GNUC__
// -------------------------------------------------------------------


// @@protoc_insertion_point(namespace_scope)


// @@protoc_insertion_point(global_scope)

#include <google/protobuf/port_undef.inc>
#endif  // GOOGLE_PROTOBUF_INCLUDED_GOOGLE_PROTOBUF_INCLUDED_objects_5f3D_2eproto
